name: Triggered Using tag

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.ref_type == 'tag' && github.event.base_ref=='refs/heads/main' }}
    steps:
      - name: Greet
        run: echo "Hello user, I am triggered because of tag push in branch ${{ github.event.base_ref }} "
        shell: bash
